### ISSUE TITLE
Add a README and LICENSE file

### ISSUE THREAD

**Issue by ifraixedes** [storj/storagenode-docker#2]
To follow the minimal good practices, this repository needs a README and a LICENSE file.

**Comment by iglesiasbrandon** [comment]
@jtolio what license should this repo have?

**Comment by jtolio** [comment]
oh, heh, i actually added a LICENSE (not having seen this issue) just last week. still need a README but i don't know if i'm that person for this repo

**Comment by iglesiasbrandon** [comment]
Added a simple readme. closing this issue

**Comment by jtolio** [comment]
@iglesiasbrandon finished it! good work
